queue_rules:
  - name: default
    conditions: []  # no extra conditions needed to get merged

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - label=mergequeue
    actions:
      queue:
        name: default
        method: squash