queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - label=mergequeue
      - check-success=say-hello-workflow
      - "check-success=ci/circleci: say-hello"
    actions:
      queue:
        name: default
        method: squash